/*
 * Copyright (c) 2025 Théo Heng
 *
 * This file is part of the drv8214_multiplatform library.
 *
 * Licensed under the MIT License. See the LICENSE file in the project root for full license information.
 */

#ifndef I2C_H
#define I2C_H

#include "Platform.h"

#ifdef DRV8214_PLATFORM_ARDUINO
    #include <Arduino.h>
    #include <Wire.h>
#endif

#ifdef DRV8214_PLATFORM_STM32
    #include "stm32fxxx_hal.h"  // Replace xx with your actual MCU family
    #include "stm32_hal.h"      // This should make the process automatic
    #include "i2c.h"           // Generated by STM32CubeMX for I2C initialization
#endif

void writeRegister(uint8_t address, uint8_t reg, uint8_t value);
uint8_t readRegister(uint8_t address, uint8_t reg);
void modifyRegister(uint8_t adress, uint8_t reg, uint8_t mask, bool enable);
void modifyRegisterBits(uint8_t address, uint8_t reg, uint8_t mask, uint8_t newValue);

#endif